version: "3.9"

services:
  conversion-node:
    build:
      context: ./conversion-service/node-converter
    container_name: conversion-node
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
    volumes:
      - ./conversion-service/node-converter:/usr/src/app:delegated
      - ./conversion-service/node-converter/package.json:/usr/src/app/package.json:delegated
      - ./conversion-service/node-converter/package-lock.json:/usr/src/app/package-lock.json:delegated
      - ./conversion-service/node-converter/uploads:/usr/src/app/uploads
    command: npm run dev
    networks:
      - conversion-net

  conversion-php:
    build:
      context: ./conversion-service/php-converter
    container_name: conversion-php
    ports:
      - "4001:9000"
    volumes:
      - ./conversion-service/php-converter/src:/var/www/html/src:delegated
      - ./conversion-service/php-converter/composer.json:/var/www/html/composer.json:delegated
      - ./conversion-service/php-converter/composer.lock:/var/www/html/composer.lock:delegated
      - ./conversion-service/php-converter/converted:/var/www/html/converted
      - ./conversion-service/node-converter/uploads:/var/www/html/uploads
    working_dir: /var/www/html
    command: php -S 0.0.0.0:9000 -t src src/index.php
    environment:
      PHP_OPCACHE_ENABLE: "0"
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: "1"
      PHP_OPCACHE_REVALIDATE_FREQ: "0"
    networks:
      - conversion-net


volumes:
  node_modules:
  php_vendor:

networks:
  conversion-net:
    driver: bridge