# .github/workflows/ci.yml
name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/**'
      - develop
      - 'release/**'
      - main
    tags:
      - 'v*.*.*'

env:
  REGISTRY: ${{ secrets.REGISTRY_URL }}

jobs:
  # 1. Lint de commits con Conventional Commits
  lint-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint Conventional Commits
        uses: wagoid/commitlint-github-action@v4
        with:
          configFile: commitlint.config.js

  # 2. Build y Test para Node y PHP
  build-and-test:
    needs: lint-commits
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [node-converter, php-converter]
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build ${{ matrix.service }}
        run: |
          docker build \
            --file ./conversion-service/${{ matrix.service }}/Dockerfile \
            --tag ${{ env.REGISTRY }}/${{ matrix.service }}:${{ github.sha }} \
            ./conversion-service/${{ matrix.service }}

      - name: Test ${{ matrix.service }}
        run: |
          IMAGE="${{ env.REGISTRY }}/${{ matrix.service }}:${{ github.sha }}"
          if [ "${{ matrix.service }}" = "node-converter" ]; then
            docker run --rm $IMAGE npm test
          else
            docker run --rm $IMAGE vendor/bin/phpunit --configuration phpunit.xml
          fi

  # 3. Escaneo de seguridad y SBOM
  security-scan:
    needs: build-and-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [node-converter, php-converter]
    steps:
      - name: Scan ${{ matrix.service }} with Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ env.REGISTRY }}/${{ matrix.service }}:${{ github.sha }}
          format: 'table'
          exit-code: '1'
          vuln-type: 'os,library'

      - name: Generate SBOM for ${{ matrix.service }}
        uses: anchore/sbom-action@v0
        with:
          image: ${{ env.REGISTRY }}/${{ matrix.service }}:${{ github.sha }}
          output-format: 'spdx-json'
          output-path: sbom-${{ matrix.service }}.json

  # 4. Push de imágenes en tags semánticos
  push-images:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: security-scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push images
        run: |
          for svc in node-converter php-converter; do
            docker push ${{ env.REGISTRY }}/${svc}:${{ github.sha }}
            docker tag ${{ env.REGISTRY }}/${svc}:${{ github.sha }} ${{ env.REGISTRY }}/${svc}:${{ github.ref_name }}
            docker push ${{ env.REGISTRY }}/${svc}:${{ github.ref_name }}
          done

  # 5. Deploy con docker-compose en main
  deploy:
    if: github.ref == 'refs/heads/main'
    needs: push-images
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Deploy stack
        run: |
          cd /ruta/al/proyecto
          docker-compose pull
          docker-compose up -d